spring:
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:softdelete}?useSSL=false
    username: ${db.uid:postgres}
    password: ${db.pwd:postgres}
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: validate